[package]
name = "rsa"
version = "0.1.0"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]
edition = "2018"

[dependencies]
rand = "0.6"
failure = "0.1"

[dependencies.num-bigint]
version = "0.2.2"
features = ["rand"]
